// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// DmxInputInverted //
// ---------------- //

#define DmxInputInverted_wrap_target 1
#define DmxInputInverted_wrap 8

static const uint16_t DmxInputInverted_program_instructions[] = {
    0x2020, //  0: wait   0 pin, 0
            //     .wrap_target
    0x20a0, //  1: wait   1 pin, 0
    0xe427, //  2: set    x, 7                   [4]
    0x4001, //  3: in     pins, 1
    0x0243, //  4: jmp    x--, 3                 [2]
    0x2020, //  5: wait   0 pin, 0
    0xa0ce, //  6: mov    isr, !isr
    0x4078, //  7: in     null, 24
    0x8020, //  8: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program DmxInputInverted_program = {
    .instructions = DmxInputInverted_program_instructions,
    .length = 9,
    .origin = -1,
};

static inline pio_sm_config DmxInputInverted_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + DmxInputInverted_wrap_target, offset + DmxInputInverted_wrap);
    return c;
}
#endif

