// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------------- //
// DmxOutputInverted //
// ----------------- //

#define DmxOutputInverted_wrap_target 3
#define DmxOutputInverted_wrap 7

static const uint16_t DmxOutputInverted_program_instructions[] = {
    0xf835, //  0: set    x, 21           side 1     
    0x0741, //  1: jmp    x--, 1                 [7] 
    0xb742, //  2: nop                    side 0 [7] 
            //     .wrap_target
    0x96a0, //  3: pull   block           side 0 [6] 
    0xa0ef, //  4: mov    osr, !osr                  
    0xfb27, //  5: set    x, 7            side 1 [3] 
    0x6001, //  6: out    pins, 1                    
    0x0246, //  7: jmp    x--, 6                 [2] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program DmxOutputInverted_program = {
    .instructions = DmxOutputInverted_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config DmxOutputInverted_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + DmxOutputInverted_wrap_target, offset + DmxOutputInverted_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif
